config/routes.rb
Chameleon::Application.routes.draw do

  require 'subdomain'

  resources :accounts do
    resources :users
  end
  resources :users
  resources :websites

  namespace :admin do |admin|
    match '/' => 'dashboard#index'
    resources :websites do
      resources :pages, :messages
    end

    resources :websites
    resources :pages
    resources :pages do
      resources :locations, :galleries, :forms, :images
    end

    resources :sessions
    resources :messages
    get 'login' => 'sessions#new', :as => 'login'
    get 'logout' => 'sessions#destroy', :as => 'logout'  
    resources :images
    resources :galleries
    resources :photos
    resources :galleries do
      resources :photos
    end
    resources :locations
    resources :forms
  end

  resources :pages do
    resources :locations, :galleries, :forms, :images
  end
  
  resources :password_resets
  resources :password_change
  get 'signup' => 'accounts#new', :as => 'signup'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  constraints(Subdomain) do
    match '/(:permalink)' => 'pages#show'
  end
  
  root :to => 'websites#index'

end

app/views/admin/pages/_contact.html.erb
<% unless (@page.forms).empty? %>

<p id="notice"><%= notice %></p>
<h2><%= @page.forms[0].heading %></h2>
<%= form_for @message, :url => {:controller => :contact, :action => :create, :permalink => params[:permalink]} do |f| %>
  
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :visitor_name, 'Your name' %><br />
    <%= f.text_field :visitor_name %>
  </div>
  <div class="field">
    <%= f.label :visitor_email, 'Your email' %><br />
    <%= f.text_field :visitor_email %>
  </div>
  <div class="field">
    <%= f.label :visitor_phone, 'Your phone' %><br />
    <%= f.text_field :visitor_phone %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit :disable_with => "Processing..." %>
  </div>
<% end %>

<% end %>

app/views/admin/pages/_form.html.erb
<%= form_for [:admin, @page] do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <%= f.label :title %>
      <%= f.text_field :title, :class => 'big field' %>

      <div style="background-color:papayawhip;margin:10px;padding:10px;">
      Page has:
      <ul>
      
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% image = Image.find_by_page_id(@page.id) %>
        <% unless image.nil? %>
          <li>
          Image <%= link_to 'Delete', admin_image_url(image), confirm: 'Are you sure?', method: :delete %>
          <%= image_tag @page.images[0].src_url(:thumb).to_s %>
          </li>
        <% end %>
       <% end %>
      
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% form = Form.find_by_page_id(@page.id) %>
        <% unless form.nil? %>
          <li>Form <%= link_to 'Edit', edit_admin_form_url(form) %> | <%= link_to 'Remove', admin_form_url(form), confirm: 'Are you sure?', method: :delete %></li>
        <% end %>
       <% end %>
      
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% gallery = Gallery.find_by_page_id(@page.id) %>
        <% unless gallery.nil? %>
          <li>Photo gallery</li>
        <% end %>
      <% end %>
      
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% map = Location.find_by_page_id(@page.id) %>
        <% unless map.nil? %>
          <li>Map pointing to: <%= map.address %> | <%= check_box_tag 'remove_map', map.id %>remove map<br />
          <% unless (@page.locations).empty? %>
            <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@page.locations[0].latitude}%2C#{@page.locations[0].longitude}" %>
          <% end %>
          </li>
        <% end %>
      <% end %>
      </ul>
      </div>

      <div style="background-color:lightgreen;margin:10px;padding:10px;">
      Add to page:
      <ul>
      
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% image = Image.find_by_page_id(@page.id) %>
        <% if image.nil? %>
          <li><%= link_to 'Image', new_admin_page_image_path(@page) %></li>
        <% end %>
       <% end %>
      
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% form = Form.find_by_page_id(@page.id) %>
        <% if form.nil? %>
          <li><%= link_to 'Contact form', new_admin_page_form_path(@page) %></li>
        <% end %>
       <% end %>
      
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% gallery = Gallery.find_by_page_id(@page.id) %>
        <% if gallery.nil? %>
          <li><%= link_to 'Photo gallery', new_admin_page_gallery_path(@page) %></li>
        <% end %>
      <% end %>
      
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% map = Location.find_by_page_id(@page.id) %>
        <% if map.nil? %>
          <li><%= link_to 'Map', new_admin_page_location_path(@page) %></li>
        <% end %>
      <% end %>
      
      </ul>
      </div>

      <%= f.label :body %>
      <%= f.text_area :body, :class => 'field', :style => "width:98%;" %>

  <div class="actions">
    <%= f.submit :disable_with => "Processing...", :class => 'submitpage' %>
  </div>
<% end %>

app/views/admin/pages/_form_backup.html.erb
<p id="notice"><%= notice %></p>

<%= form_for [:admin, @page] do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <%= f.label :title %>
      <%= f.text_field :title, :class => 'big field' %>

      <div style="background-color:lightgreen;margin:10px;padding:10px;">
      Add to page:
      <ul>
      <li>
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% image = Image.find_by_page_id(@page.id) %>
        <% if image.nil? %>
          <%= link_to 'Image', new_admin_page_image_path(@page) %>
        <% else %>
          This page contains an image <%= link_to 'Delete', admin_image_url(image), confirm: 'Are you sure?', method: :delete %>
          <%= image_tag @page.images[0].src_url(:thumb).to_s %>
        <% end %>
       <% end %>
       </li>

      <li>
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% form = Form.find_by_page_id(@page.id) %>
        <% if form.nil? %>
          <%= link_to 'Contact form', new_admin_page_form_path(@page) %>
        <% else %>
          This page contains a form <%= link_to 'Remove', admin_form_url(form), confirm: 'Are you sure?', method: :delete %>
        <% end %>
       <% end %>
       </li>

      <li>
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% gallery = Gallery.find_by_page_id(@page.id) %>
        <% if gallery.nil? %>
          <%= link_to 'Photo gallery', new_page_gallery_path(@page) %>
        <% else %>
          This page contains a photo gallery
        <% end %>
      <% end %>
      </li>

      <li>
      <% if params[:action] == 'edit' or params[:action] == 'update' %>
        <% map = Location.find_by_page_id(@page.id) %>
        <% if map.nil? %>
          <%= link_to 'Map', new_admin_page_location_path(@page) %><br />
        <% else %>
          This page contains a Map pointing to: <%= map.address %> | <%= check_box_tag 'remove_map', map.id %>remove map<br />
          <% unless (@page.locations).empty? %>
            <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@page.locations[0].latitude}%2C#{@page.locations[0].longitude}" %>
          <% end %>
        <% end %>
      <% end %>
      </li>
      </ul>
      </div>

      <%= f.label :body %>
      <%= f.text_area :body, :class => 'field', :style => "width:98%;" %>

  <div class="actions">
    <%= f.submit :disable_with => "Processing...", :class => 'submitpage' %>
  </div>
<% end %>

app/views/admin/pages/_images.html.erb
<% unless (@page.images).empty? %>
  <style>
  div.page_image{
    float:right;
  }
  div.page_image img{
    background-color:white;
    border:1px solid #CCC;
    padding:5px;
  }
  </style>
  <div class="page_image"><%= image_tag @page.images[0].src_url(:medium).to_s %></div>
<% end %>

app/views/admin/pages/_location.html.erb
<% unless (@page.locations).empty? %>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@page.locations[0].latitude}%2C#{@page.locations[0].longitude}" %>
<% end %>

app/views/admin/pages/_pages.html.erb
<ul>
<% @pages.each do |page| %>
  <li><%= link_to page.title, page_path(page) %></li>
<% end %>
</ul>

app/views/admin/pages/edit.html.erb
<h2>Edit page</h2>

<%= render 'form' %>

app/views/admin/pages/index.html.erb
<h2>Website Pages</h2>

<p><%= link_to 'Add a new page', new_admin_website_page_path(current_website)  %></p>

<div id="wordsRow" class="contentRow">

<% @pages.each do |page| %>
    <li>
      <%= page.title %> / <%= link_to 'Edit', edit_admin_page_path(page) %> | <%= link_to 'Delete', page, confirm: 'Are you sure? This action cannot be undone.', method: :delete %>
    </li>
<% end %>


<!-- <p><%= link_to 'All Websites', root_url(:subdomain => false) %></p> -->


</div>

app/views/admin/pages/new.html.erb
<h2 class="rowTitle">New page</h2>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/admin/pages/show_plain.html.erb
<!--
<div id="content">
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Body:</b>
  <%= @page.body %>
</p>
</div>
-->
<!-- div content ends -->




    <div id="column-wrapper"><!-- Start #column-wrapper --> 


    <div id="left-column"><!-- Start #left-column --> 
        <div id="hero"> 
            <a href="#"><img src="<%= theme_asset_path %>img-hero.png" border="0" width="692" height="323"></a> 
            <a href="#"></a> 
            <a href="#"></a> 
            <a href="#"></a> 
        </div> 
    </div> 
    <!-- End #left-column" --> 
    
    <div id="right-column"><!-- Start #right-column --> 
        <div id="online-banking"><!-- Start #online-banking --> 
            <h2>Secure Online Banking</h2> 
            <form action="https://www.netteller.com/tx-communitybank/login.cfm" name="login" method="post"> 
                    <div class="ob-row"> <!-- Start .ob-row --> 
                        <label for="userid">Username:</label> 
                        <input name="ID" type="text" class="input" /> 
                    </div> 
                    <!-- End .ob-row --> 
                    <div class="ob-row"> <!-- Start .ob-row --> 
                        <label for="password">Password:</label> 
                        <input name="PIN" type="password" class="input" /> 
                    </div> 
                    <!-- End .ob-row --> 
                    <input name="submit" type="image" id="submitBtn" value="Submit" src="/design/img-login-btn.png" /> 
                </form> 
                <ul> 
                    <li><a href="/services-bill-pay.htm">Bill Pay</a></li> 
                    <li><a href="/internet-banking-enroll.htm">Enroll</a></li> 
                    <li><a href="/services-online-banking.htm">Learn More</a></li> 
                </ul> 
        </div> 
        <!-- End #online-banking -->        
    </div> 
    <!-- End #right-coulmn --> 


    <div id="features"><!-- Start #feature -->  
        <div class="splash-feature"> 
            <h2>Save time. Save money. Save trees</h2> 
            <div class="splash-feature-image"> 
                <img src="<%= theme_asset_path %>img-woman-phone-laptop.png" border="0" width="170" height="121"> 
            </div> 
            <div class="splash-feature-text"> 
                <p> 
       <strong>E-Statements</strong> make sense and cents-save time, paper and postage with electronic statements. To sign up for <strong>E-Statements</strong> log on to TCB Bank Online today!
    </p> 
            </div> 
            <a href="/services-estatements.htm">Start Now! <img src="img-arrow-btn.png" alt="" width="24" height="24" border="0" /></a> 
        </div> 
<div class="splash-feature"> 
            <h2>A Card to simplify your lifestyle</h2> 
            <div class="splash-feature-image"> 
                <img src="<%= theme_asset_path %>img-credit-card.png" border="0" width="262" height="133"> 
            </div> 
            <div class="splash-feature-text"> 
                <p> 
       <strong>Texas StarCard</strong> gives you a faster, more convenient way to buy the products and services you need. It&#39;s the checking, withdrawing, depositing, and transferring funds card all in one.
    </p> 
            </div> 
            <a href="/services-atm-debit-cards.htm">Find out more <img src="/design/img-arrow-btn.png" alt="" width="24" height="24" border="0" /></a> 
        </div> 
<div class="splash-feature"> 
            <h2>TCB Scene and Heard</h2> 
            <div class="splash-feature-image"> 
                <img src="<%= theme_asset_path %>img-lineup.png" border="0" width="273" height="121"> 
            </div> 
            <div class="splash-feature-text"> 
                <p> 
       E-Statements make sense and cents-save time, paper and postage with electronic statements. To sign up for E-Statements today log on to you TCB Bank Online today!
    </p> 
            </div> 
            <a href="/tcb-scene-heard.htm">Find out more <img src="/design/img-arrow-btn.png" alt="" width="24" height="24" border="0" /></a> 
        </div> 
    </div><!-- End #features --> 
    
    
    
    </div><!-- End #column-wrapper -->

app/views/admin/pages/show_practical.html.erb
	<div id="container" class="template-aboutus"> 
		<div id="content" role="main" class="layout"> 
 
							
									
											<h1 class="entry-title supporting"><%= @page.title %></h1> 
						<div class="supporting x6"> 
							<p> 
								Two pharma researchers who wanted to become more involved in research: to spend more time with clients and respondents (and less time in meetings).							</p> 
						</div> 
										
				
				<div id="post-41" class="post-41 page type-page status-publish format-standard hentry col x6"> 
 
					<div class="entry-content"> 
						
						<p>We’ve done a lot of research over the years, but we’ve also worked out­side research, as a tour-guide; a deck-hand; in ski resorts and of course, at well-known <span class="caps">UK</span> mar­ket research agen­cies. We’re inter­ested in new approaches to research, about engag­ing our clients in what we do and in deliv­er­ing well designed reports and pre­sen­ta­tions that impact client teams.</p> 
<h2>HEADING NUMBER 2</h2>
<p><%= @page.body %></p>

<h2><span class="caps">FRESH</span> <span class="caps">APPROACH</span></h2>

<p>We’re new.  And yet expe­ri­enced at the same time…</p> 
<p>You’ll find us talk­ing about our approach and phi­los­o­phy to mar­ket research and not our years of expe­ri­ence in dif­fer­ent ther­apy areas nor how many coun­tries we’ve recently under­taken research in. We’ll make the most of the respon­dents we talk to – above and beyond the topic guide. And we’ll do our utmost to ensure that we eval­u­ate the best new approaches, rec­om­mend dif­fer­ent ways of doing what we’ve done many times before and that we chal­lenge our clients.</p> 

<h2><span class="caps">OPEN</span> <span class="caps">MINDED</span></h2> 
<p>There’s more than one way to skin a cat.</p> 
<p>And there’s more than one way to address a research issue – no mat­ter how sim­i­lar it is to oth­ers that have pre­ceded it. You’ll not hear us say: ‘That’s the approach we use here’.  We’re open to new approaches and tech­niques that address old (and new) prob­lems. We con­sider all angles and approaches – so long as they work.</p> 

<h2><span class="caps">OUR</span> <span class="caps">BEGINNINGS</span></h2> 
<p><img class="alignnone size-template_a wp-image-269" title="Blandfords+Cafe" src="http://brookspumfreyresearch.co.uk/wp/wp-content/uploads/2011/05/Blandfords+Cafe-633x347.jpg" alt="" width="633" height="347" /><br /> 
Talk­ing and ask­ing ques­tions.  Won­der­ing if we could cre­ate a bet­ter pharma mar­ket research agency.  Think­ing how we might do the lit­tle things bet­ter. We spent many hours at Bland­fords in cen­tral Lon­don dis­cussing our plans.  And we rec­om­mend the mixed omelette and chips.</p> 
						
												
					</div><!-- .entry-content --> 
				</div><!-- #post-## --> 
				
				
								
				<div class="col x3"> 
																<div id="user-2" class="user clearfix"> 
							<div class="avatar"> 
								<span></span> 
								<img alt='' src='http://0.gravatar.com/avatar/a7be269d937ae3f701f0352141c453ed?s=114&amp;d=http%3A%2F%2F0.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D114&amp;r=G' class='avatar avatar-114 photo' height='114' width='114' />							</div> 
							<h3> 
								Bridget Pumfrey							</h3> 
							<p> 
															</p> 
						</div> 
											<div id="user-3" class="user clearfix"> 
							<div class="avatar"> 
								<span></span> 
								<img alt='' src='http://1.gravatar.com/avatar/b579457ddb3f5d86e273e4f8eac76655?s=114&amp;d=http%3A%2F%2F1.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D114&amp;r=G' class='avatar avatar-114 photo' height='114' width='114' />							</div> 
							<h3> 
								Matt Brooks							</h3> 
							<p> 
															</p> 
						</div> 
									</div> 
 
			
		</div><!-- #content --> 
		
									
	</div><!-- #container --> 
 

app/views/admin/pages/show_standard.html.erb
<%= simple_format @page.body %>

<%= render 'pages/images' %>

<%= render 'pages/galleries' %>

<%= render 'pages/location' %>

<%= render 'pages/contact' %>

app/views/admin/pages/show_teach.html.erb
<div id="main"> 
		<div id="container"> 
			<div id="content"> 
   			<div id="post-2" class="post-2 page type-page status-publish hentry"> 
					<div class="entry-content"> 
						<div id="lcol">
<h2><%= @page.title %></h2>

<%= @page.body %>

<% unless (@page.locations).empty? %>
<%= @page.locations %>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@page.locations[0].latitude}%2C#{@page.locations[0].longitude}" %>
<% end %>


<% if true %>
<% end %>

</div>



<div id="rcol">
<img src="<%= theme_asset_path %>master-plan-points.jpg" alt="" />
<p>
Rent-a-design is a Web design firm that specializes in affordable and practical Websites for small to medium-size businesses. 
You rent the design and pay a small monthly subscription to keep on using it. There is no committment and you can cancel at any time.
</p>
<strong>For more information on how we can help you setup your online presence, <a class="blue" href="/" >click here</a></strong>
</div>																	

<div class="clear"></div> 
					</div><!-- .entry-content --> 
				</div><!-- #post-## --> 
 
			</div><!-- #content --> 
		</div><!-- #container --> 
 
	</div><!-- #main --> 
	</div><!-- wrapper --> 

app/views/admin/pages/show_tx_clone.html.erb
<!--
<div id="content">
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Body:</b>
  <%= @page.body %>
</p>
</div>
-->
<!-- div content ends -->




    <div id="column-wrapper"><!-- Start #column-wrapper --> 


    <div id="left-column"><!-- Start #left-column --> 
        <div id="hero"> 
            <a href="#"><img src="<%= theme_asset_path %>img-hero.png" border="0" width="692" height="323"></a> 
            <a href="#"></a> 
            <a href="#"></a> 
            <a href="#"></a> 
        </div> 
    </div> 
    <!-- End #left-column" --> 
    
    <div id="right-column"><!-- Start #right-column --> 
        <div id="online-banking"><!-- Start #online-banking --> 
            <h2>Secure Online Banking</h2> 
            <form action="https://www.netteller.com/tx-communitybank/login.cfm" name="login" method="post"> 
                    <div class="ob-row"> <!-- Start .ob-row --> 
                        <label for="userid">Username:</label> 
                        <input name="ID" type="text" class="input" /> 
                    </div> 
                    <!-- End .ob-row --> 
                    <div class="ob-row"> <!-- Start .ob-row --> 
                        <label for="password">Password:</label> 
                        <input name="PIN" type="password" class="input" /> 
                    </div> 
                    <!-- End .ob-row --> 
                    <input name="submit" type="image" id="submitBtn" value="Submit" src="/design/img-login-btn.png" /> 
                </form> 
                <ul> 
                    <li><a href="/services-bill-pay.htm">Bill Pay</a></li> 
                    <li><a href="/internet-banking-enroll.htm">Enroll</a></li> 
                    <li><a href="/services-online-banking.htm">Learn More</a></li> 
                </ul> 
        </div> 
        <!-- End #online-banking -->        
    </div> 
    <!-- End #right-coulmn --> 


    <div id="features"><!-- Start #feature -->  
        <div class="splash-feature"> 
            <h2>Save time. Save money. Save trees</h2> 
            <div class="splash-feature-image"> 
                <img src="<%= theme_asset_path %>img-woman-phone-laptop.png" border="0" width="170" height="121"> 
            </div> 
            <div class="splash-feature-text"> 
                <p> 
       <strong>E-Statements</strong> make sense and cents-save time, paper and postage with electronic statements. To sign up for <strong>E-Statements</strong> log on to TCB Bank Online today!
    </p> 
            </div> 
            <a href="/services-estatements.htm">Start Now! <img src="img-arrow-btn.png" alt="" width="24" height="24" border="0" /></a> 
        </div> 
<div class="splash-feature"> 
            <h2>A Card to simplify your lifestyle</h2> 
            <div class="splash-feature-image"> 
                <img src="<%= theme_asset_path %>img-credit-card.png" border="0" width="262" height="133"> 
            </div> 
            <div class="splash-feature-text"> 
                <p> 
       <strong>Texas StarCard</strong> gives you a faster, more convenient way to buy the products and services you need. It&#39;s the checking, withdrawing, depositing, and transferring funds card all in one.
    </p> 
            </div> 
            <a href="/services-atm-debit-cards.htm">Find out more <img src="/design/img-arrow-btn.png" alt="" width="24" height="24" border="0" /></a> 
        </div> 
<div class="splash-feature"> 
            <h2>TCB Scene and Heard</h2> 
            <div class="splash-feature-image"> 
                <img src="<%= theme_asset_path %>img-lineup.png" border="0" width="273" height="121"> 
            </div> 
            <div class="splash-feature-text"> 
                <p> 
       E-Statements make sense and cents-save time, paper and postage with electronic statements. To sign up for E-Statements today log on to you TCB Bank Online today!
    </p> 
            </div> 
            <a href="/tcb-scene-heard.htm">Find out more <img src="/design/img-arrow-btn.png" alt="" width="24" height="24" border="0" /></a> 
        </div> 
    </div><!-- End #features --> 
    
    
    
    </div><!-- End #column-wrapper -->