config/routes.rb
Chameleon::Application.routes.draw do

  require 'subdomain'

  resources :accounts do
    resources :users
  end
  resources :users
  resources :websites

  namespace :admin do |admin|
    match '/' => 'dashboard#index'
    resources :websites do
      resources :pages, :messages
    end

    resources :websites
    resources :pages
    resources :pages do
      resources :locations, :galleries, :forms, :images
    end

    resources :sessions
    resources :messages
    get 'login' => 'sessions#new', :as => 'login'
    get 'logout' => 'sessions#destroy', :as => 'logout'  
    resources :images
    resources :galleries
    resources :photos
    resources :galleries do
      resources :photos
    end
    resources :locations
    resources :forms
  end

  resources :pages do
    resources :locations, :galleries, :forms, :images
  end
  
  resources :password_resets
  resources :password_change
  get 'signup' => 'accounts#new', :as => 'signup'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  constraints(Subdomain) do
    match '/(:permalink)' => 'pages#show'
  end
  
  root :to => 'websites#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :photos, :dependent => :destroy
  belongs_to :website
  belongs_to :page
  validates :name, :presence => true
  accepts_nested_attributes_for :photos
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < AdminController

  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html
    end
  end

  def show
    @gallery = Gallery.find(params[:id])
    @photos = Photo.all(:conditions => ["gallery_id == ?", params[:id]], :order => "created_at DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  def new
    # @gallery = Gallery.new
    unless params[:page_id]
      @pages = Page.all
    end
    respond_to do |format|
      format.html
      # format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
    @pages = Page.all
  end

  def create
    # @gallery = Gallery.new(params[:gallery])
    # @gallery = Gallery.new(params[:gallery])
    @gallery.page_id = params[:page_id]
    respond_to do |format|
      if @gallery.save
        format.html { redirect_to admin_gallery_url(@gallery), notice: 'Gallery was successfully created.' }
        # format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        # format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @gallery = Gallery.find(params[:id])
    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to edit_admin_gallery_url(@gallery), notice: 'Gallery was successfully updated.' }
        # format.json { head :ok }
      else
        format.html { render action: "edit" }
        # format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to admin_galleries_url }
      format.json { head :ok }
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])
    @photos = Photo.all(:conditions => ["gallery_id == ?", params[:id]], :order => "created_at DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    unless params[:page_id]
      @pages = Page.all
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
    @pages = Page.all
  end

  # POST /galleries
  # POST /galleries.json
  def create
    # @gallery = Gallery.new(params[:gallery])
    @gallery = Gallery.new(params[:gallery])
    @gallery.page_id = params[:page_id]

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/admin/galleries/_form.html.erb
<%= form_for [:admin, @gallery] do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
	  <%= f.label :page_id, 'Move to page' %><br />
	  <%= f.collection_select :page_id, @pages, :id, :title %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="actions">
    <%= f.submit :disable_with => "Processing..." %>
  </div>
<% end %>

app/views/admin/galleries/_nested_form.html.erb
<h3>i'm the nested one</h3>

<%= form_for @gallery, :url => admin_page_galleries_path(@page) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="actions">
    <%= f.submit :disable_with => "Processing..." %>
  </div>
<% end %>

app/views/admin/galleries/edit.html.erb
<h1>Editing gallery</h1>

<p><%= link_to 'Add a photo', new_admin_gallery_photo_path(@gallery) %></p>

<% if params[:page_id] %>
  <%= render 'nested_form' %>  
<% else %>
  <%= render 'form' %>
<% end %>

app/views/admin/galleries/index.html.erb
<h1>Listing galleries</h1>


<style>
table#galleries th, table#galleries td{
  border:1px solid #CCC;
  padding:5px;
}
</style>


<table id="galleries">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Description</th>
    <th>Webpage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr>
    <td>
      <% if gallery.photos[0] %>
        <%= image_tag gallery.photos[0].image_url(:thumb).to_s %>
      <% end %>
    </td>
    
    <td><%= gallery.name %> (<%= gallery.photos.count %>)</td>
    <td><%= gallery.description %></td>
    <% page = Page.find(gallery.page_id) %>
    <td><%= page.title %></td>
    <td><%= link_to 'Show', admin_gallery_path(gallery) %></td>
    <td><%= link_to 'Edit', edit_admin_gallery_path(gallery) %></td>
    <td><%= link_to 'Destroy', admin_gallery_path(gallery), confirm: 'Are you sure?', method: :delete %></td>
    
    
    
    
    
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery', new_admin_gallery_path %>

app/views/admin/galleries/new.html.erb
<h1>New gallery</h1>

<% if params[:page_id] %>
  <%= render 'nested_form' %>  
<% else %>
  <%= render 'form' %>
<% end %>

app/views/admin/galleries/show.html.erb
<p>
  <b>Name:</b>
  <%= @gallery.name %>
</p>

<p>
  <b>Description:</b>
  <%= @gallery.description %>
</p>

<p>
  <b>Website:</b>
  <%= @gallery.website_id %>
</p>

<hr />

<%= link_to 'Add a photo', new_admin_gallery_photo_path(@gallery) %>

<hr />

<style>
ul.imggrid {
  padding: 0;
  list-style: none;
  margin: 0 auto;
  /* width: 495px; */
  width:550px;
  }

.imggrid li {
    background-color:white;
    float: left;
    /* padding: 1px; */
    padding:8px;
    border: 1px solid #cbcad0;
    margin: 0 5px 10px 5px;
    list-style: none;
    
    display:block;
    width:100px;
    height:120px;
    
    } 

.imggrid_display {
   padding: 20px;
   margin: 0 auto;
   width: 513px; 
   /*these two properties will be inherited by .portfolio h2 and .portfolio p */
   font-family: 'GraublauWeb', arial, serif; 
   text-align: center;
  }

  /* .post-body is only for those who are on Blogger, or all others please skip 
     it and write your selector as "div.imggrid_display h2" without the quotes
  */
  .post-body div.imggrid_display h2 {
     padding: 0; margin: 0;
     clear: both;
     font-size: 35px;
     font-weight: normal;
     color: #58595b;
     background: none;
     font-family: 'GraublauWeb', arial, serif;  
     /* reset for cascade effects that are trickling down to me 
       from other h2's 
    */
     text-transform: none;
     letter-spacing: normal;
     }
  
  .imggrid_display p {
      margin:0; padding: 0;
      font-size: 8pt;
      color: #58595b;
      }
  
/* sprites for imggrid */
.imggrid a {
    /* background: url('images/spritebitmaps.jpg') no-repeat; */
    /* height: 150px;
    width: 150px; */
    /* height: 100px;
    width: 100px;
    display: block; */
    }
</style>

<% if @photos.blank? %>
  <p>No photos in this gallery</p>
<% else %>
  
<div class="imggrid_display">
  <ul class="imggrid">
  <% for photo in @photos %>
    <li>
      <a href="<%= photo.image_url(:medium).to_s %>" class="group" title="<%= photo.title %>" ><%= image_tag photo.image_url(:thumb).to_s, :class => 'gallery_photo' %></a>
      
      <p>
        <%= photo.title %><br />
        <%= link_to 'edit', edit_admin_gallery_photo_path(@gallery, photo) %> | <%= link_to 'remove', admin_photo_url(photo), confirm: 'Are you sure?', method: :delete %>
      </p>
    </li>
  <% end %>
  </ul>
</div>
  
<% end %>