config/routes.rb
Chameleon::Application.routes.draw do

  require 'subdomain'

  resources :accounts do
    resources :users
  end
  resources :users
  resources :websites

  namespace :admin do |admin|
    match '/' => 'dashboard#index'
    resources :websites do
      resources :pages, :messages
    end

    resources :websites
    resources :pages
    resources :pages do
      resources :locations, :galleries, :forms, :images
    end

    resources :sessions
    resources :messages
    get 'login' => 'sessions#new', :as => 'login'
    get 'logout' => 'sessions#destroy', :as => 'logout'  
    resources :images
    resources :galleries
    resources :photos
    resources :galleries do
      resources :photos
    end
    resources :locations
    resources :forms
  end

  resources :pages do
    resources :locations, :galleries, :forms, :images
  end
  
  resources :password_resets
  resources :password_change
  get 'signup' => 'accounts#new', :as => 'signup'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  constraints(Subdomain) do
    match '/(:permalink)' => 'pages#show'
  end
  
  root :to => 'websites#index'

end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chameleon</title>
  <%= stylesheet_link_tag "admin/application" %>
  <%= stylesheet_link_tag "fancybox" %>

  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>


<script type="text/javascript">
$(document).ready(function() {
  
	/* Apply fancybox to multiple items */
	
	$("a.group").fancybox({
		'transitionIn'	:	'elastic',
		'transitionOut'	:	'elastic',
		'speedIn'		:	600, 
		'speedOut'		:	200, 
		'overlayShow'	:	false
	});
	
});
</script>


</head>
<body>
<%= debug params %>
<%= debug request.referrer %>
		<ul>
      <li>
        Website: <%= current_website.name %> <%= link_to 'View your Website', root_url(:subdomain => current_website.subdomain), :target => '_blank' %>
      </li>			
			<li>
			  Signed in as <%= current_user.username %>
			</li>
			<li>
				<%= link_to 'Log out', admin_logout_path %>
			</li>
		</ul>

		<ul>
	    <li><%= link_to 'Pages', admin_pages_path %></li>
	    <!-- <li><%= link_to 'Images', admin_images_path %></li> -->
			<li><%= link_to 'Galleries', admin_galleries_path %></li>
			<!-- <li><%= link_to 'Forms', admin_forms_path %></li> -->
			<li><%= link_to 'Messages', admin_messages_path %>
			  <% unless unread_messages_count == 0 %>
			    (<%= unread_messages_count %>)
			  <% end %>
			</li>
			<li><%= link_to 'Website Settings', edit_admin_website_path(current_website) %></li>
		</ul>


<div id="container">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</div>


<div id="footer">
	<p> &copy; 2011 LeonelOnRails</p>
</div>

</body>
</html>