config/routes.rb
Chameleon::Application.routes.draw do

  require 'subdomain'

  resources :accounts do
    resources :users
  end
  resources :users
  resources :websites

  namespace :admin do |admin|
    match '/' => 'dashboard#index'
    resources :websites do
      resources :pages, :messages
    end

    resources :websites
    resources :pages
    resources :pages do
      resources :locations, :galleries, :forms, :images
    end

    resources :sessions
    resources :messages
    get 'login' => 'sessions#new', :as => 'login'
    get 'logout' => 'sessions#destroy', :as => 'logout'  
    resources :images
    resources :galleries
    resources :photos
    resources :galleries do
      resources :photos
    end
    resources :locations
    resources :forms
  end

  resources :pages do
    resources :locations, :galleries, :forms, :images
  end
  
  resources :password_resets
  resources :password_change
  get 'signup' => 'accounts#new', :as => 'signup'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  constraints(Subdomain) do
    match '/(:permalink)' => 'pages#show'
  end
  
  root :to => 'websites#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :website
  belongs_to :page
  
  validates :website_id, :presence => true
  validates :src, :presence => true
  # validates :page_id, :presence => true
  
  mount_uploader :src, ImageUploader
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < AdminController

  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html
    end
  end

  def show
    # @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  def new
    # @image = Image.new
    @pages = Page.where("website_id = ?", current_website.id)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  def edit
    # @image = Image.find(params[:id])
    @pages = current_website.pages
  end

  def create
    # @image = Image.new(params[:image])
    @image.website_id = current_website.id
    if params[:page_id]
      @image.page_id = params[:page_id]
    end

    respond_to do |format|
      if @image.save
        format.html { redirect_to edit_admin_page_url(params[:page_id]), notice: 'Image was successfully created.' }
        # format.html { redirect_to (:back), notice: 'Image was successfully created.' }
        # format.html { redirect_to admin_image_url(@image), notice: 'Image was successfully created.' }
        # format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        # format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    # @image = Image.find(params[:id])
    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        # format.json { head :ok }
      else
        format.html { render action: "edit" }
        # format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    # @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to (:back), notice: 'Image was successfully deleted.' }
      # format.html { redirect_to admin_images_url, notice: 'Image was successfully deleted.' }
      # format.json { head :ok }
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
    @pages = current_website.pages
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])
    @image.website_id = current_website.id
    if params[:page_id]
      @image.page_id = params[:page_id]
    end

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :ok }
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/admin/images/_form.html.erb
<%= form_for [:admin, @image], :html => {:multipart => true} do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alt %><br />
    <%= f.text_field :alt %>
  </div>

  <% unless params[:page_id] %>
  <div class="field">
	  <%= f.label :page_id, 'Page' %><br />
	  <%= f.collection_select :page_id, @pages, :id, :title, {:include_blank => ' - Please select - '} %>
  </div>
  <% end %>

  <div class="field">
    <%= f.file_field :src %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/images/_nested_form.html.erb
<h3>This is the nested form</h3>
<%= form_for @image, :url => admin_page_images_path(@page), :html => {:multipart => true} do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alt %><br />
    <%= f.text_field :alt %>
  </div>
  <div class="field">
    <%= f.file_field :src %>
  </div>
  <div class="actions">
    <%= f.submit 'Upload', :disable_with => "Processing..." %>
  </div>
<% end %>

app/views/admin/images/edit.html.erb
<h1>Editing image</h1>

<% if params[:page_id] %>
  <%= render 'nested_form' %>  
<% else %>
  <%= render 'form' %>
<% end %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/admin/images/index.html.erb
<h1>Listing images</h1>

<style>
table#images th, table#images td{
  border:1px solid #CCC;
  padding:5px;
}
</style>

<table id="images">
  <tr>
    <th></th>
    <th>Alt</th>
    <th>Page</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td>
      <%= image_tag image.src_url(:thumb).to_s %>
    </td>
    <td><%= image.alt %></td>
    
    <% if image.page_id %>
      <% page = Page.find(image.page_id) %>
      <td><%= page.title %></td>
    <% else %>
      <td></td>
    <% end %>

    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_admin_image_path(image) %></td>
    <td><%= link_to 'Destroy', admin_image_url(image), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_admin_image_path %>

app/views/admin/images/new.html.erb
<h1>New image</h1>

<% if params[:page_id] %>
  <%= render 'nested_form' %>  
<% else %>
  <%= render 'form' %>
<% end %>

<%= link_to 'Back', admin_images_path %>

app/views/admin/images/show.html.erb
<p>
  <b>Alt:</b>
  <%= @image.alt %>
</p>

<p>
  <%= image_tag @image.src_url(:thumb).to_s %>
</p>

<p>
  <%= image_tag @image.src_url(:small).to_s %>
</p>

<p>
  <%= image_tag @image.src_url(:medium).to_s %>
</p>

<%= link_to 'Edit', edit_admin_image_path(@image) %> |
<%= link_to 'Back', admin_images_path %>